#!/usr/bin/env ruby
#require 'command_line/global'
require 'open3'

p ARGV
p url = ARGV[0]
out, err, status = Open3.capture3 "wslpath -w #{url}"
p path = out

#comm = "explorer.exe #{path}"
comm = "powershell.exe /c start #{path}"
puts comm
system comm
