#!/usr/bin/env python3
import argparse
import subprocess

class Edit:
    def __init__(self, file):
        comm = f"code {file}"
        print(comm)
        subprocess.run(comm, shell=True)

class List:
    def __init__(self, file):
        comm = f"batcat --theme Coldark-Cold {file}"
        print(comm)
        subprocess.run(comm, shell=True)

def main():
    parser = argparse.ArgumentParser(description="File editor and viewer")
    parser.add_argument('-e', '--edit', metavar='FILE', help='edit FILE by vscode')
    parser.add_argument('-l', '--list', metavar='FILE', help='cat FILE with batcat')

    args = parser.parse_args()

    if args.edit:
        Edit(args.edit)
    if args.list:
        List(args.list)

if __name__ == "__main__":
    main()
